site_name: GloboDocs
site_description: Portal Corporativo de Documentação e Base de Conhecimento - Globo Pharma
site_author: Marcelo Diniz - Analista de Infraestrutura de TI
site_url: https://github.com/GloboPharma/GloboDocs

repo_url: https://github.com/GloboPharma/GloboDocs
repo_name: GloboPharma/GloboDocs
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/Logo-BR-GD.jpg
  favicon: assets/favicon.png
  language: pt-BR

  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Modo claro
features:
  - navigation.instant
  - navigation.tracking
  - navigation.top
  - toc.integrate
  - search.highlight
  - search.suggest
  - content.code.copy

plugins:
  - search

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  - Governança:
      - Escopo: governanca/escopo.md
      - Gestão de Mudanças: governanca/gestao-de-mudancas.md
      - Matriz RACI: governanca/matriz-raci.md
      - GAP Analysis: governanca/gap-analysis.md
      - Política de Documentação: governanca/politica-de-documentacao.md
      - Boas Práticas de Documentação: governanca/melhores-praticas.md
      
  - Administrativo:

    - Comercial:
      - Normas: comercial/normas/index.md
      - Procedimentos: comercial/procedimentos/index.md

    - Financeiro:
      - Normas: financeiro/normas/index.md
      - Procedimentos: financeiro/procedimentos/index.md

    - Fiscal:
      - Normas: fiscal/normas/index.md
      - Procedimentos: fiscal/procedimentos/index.md

    - Gente e Gestão:
      - Normas: gente-e-gestao/normas/index.md
      - Procedimentos: gente-e-gestao/procedimentos/index.md

    - Qualidade:
      - Normas: qualidade/normas/index.md
      - Procedimentos: qualidade/procedimentos/index.md
      - Registros: qualidade/registros/index.md

    - Tecnologia da Informação:
      - Infraestrutura:
          - Procedimentos:
              - Firewall: ti/infraestrutura/procedimentos/firewall.md
              - Servidores: ti/infraestrutura/procedimentos/servidores.md
              - Telefonia: ti/infraestrutura/procedimentos/telefonia.md
              - Certificados SSL: ti/infraestrutura/procedimentos/certificados-ssl.md              
          - Configurações:
              - Firewall: ti/infraestrutura/configuracoes/firewall.md
              - Servidores: ti/infraestrutura/configuracoes/servidores.md
              - Telefonia: ti/infraestrutura/configuracoes/telefonia.md
      - Sistemas:
          - Procedimentos:
              - Beas: ti/sistemas/procedimentos/beas.md
              - Cogtive: ti/sistemas/procedimentos/cogtive.md
              - Glpi: ti/sistemas/procedimentos/glpi.md
              - Sap: ti/sistemas/procedimentos/sap.md
              - Sesuite: ti/sistemas/procedimentos/sesuite.md
              - Starsoft: ti/sistemas/procedimentos/starsoft.md
              - Suricato: ti/sistemas/procedimentos/suricato.md
              - WMS: ti/sistemas/procedimentos/wms.md
          - Configurações:
              - Beas: ti\sistemas\configuracoes/beas/beas.md
              - Cogtive: ti/sistemas/configuracoes/cogtive/cogtive.md
              - GLPI: ti/sistemas/configuracoes/glpi/glpi.md
              - SAP:
                  - SAP: ti/sistemas/configuracoes/sap/sap.md
                  - Cadastro de Representantes: ti/sistemas/configuracoes/sap/cadastro-representantes/cadastro-representantes.md
              - SEsuite: ti/sistemas/configuracoes/sesuite/sesuite.md
              - Starsoft: ti/sistemas/configuracoes/starsoft/starsoft.md
              - Suricato: ti/sistemas/configuracoes/suricatoo/surica.md
              - WMS: ti/sistemas/configuracoes/wms/wms.md
              - Controle de Travas: ti/sistemas/configuracoes/controle de travas/aster.md
  - Fabrica:

    - Expedicao:
      - Normas: expedicao/normas.md
      - Procedimentos: expedicao/procedimentos.md

    - Qualidade:
      - Normas: qualidade/normas/index.md
      - Procedimentos: qualidade/procedimentos/index.md
      - Registros: qualidade/registros/index.md

    - Produção:
      - Procedimentos: producao/procedimentos/index.md
      - Normas: producao/normas/index.md

  - Projetos:
    - Infraestrutura:
              - Qualificação de Infraestrutura: projetos/infraestrutura/qualificacao-infra.md
              - Politicas de SI: projetos/infraestrutura/politicas-si.md
              - Controle de Cotas de Armazenamento: projetos/infraestrutura/controle-cotas.md
              - Revisão de Configurações do Ambiente Google: projetos/infraestrutura/ambiente-google.md
              - Revisão de Configurações do Ambiente BitDefender: projetos/infraestrutura/ambiente-bitdefender.md
              - Telefonia IP: projetos/infraestrutura/telefonia-ip.md
              - Integração SAP/AD: projetos/infraestrutura/integra-sap-ad.md
              - Documentação Sistêmica: projetos/infraestrutura/documentação-sistemica.md
    - Helpdesk:
              - Inventario de Softwares: projetos/HelpDesk/inventario-softwares.md
              - Laudo Equipamentos Produção: projetos/HelpDesk//laudo-producao.md
              - Troca de Equipamentos Depreciados: projetos/HelpDesk/depreciados.md
    - Sistemas:
              - Apontamentos Parciais - Produção: ti/sistemas/cogtive.md
              - BI: ti/sistemas/cogtive.md
              - Caixa Fracionada - WMS: ti/sistemas/cogtive.md
              - Controle de Acesso Suricato: ti/sistemas/cogtive.md
              - Controle de Despesas Onfly: ti/sistemas/cogtive.md
              - GPS: ti/sistemas/cogtive.md
              - Gestão de Usuários/IA: ti/sistemas/cogtive.md
              - Integração Balanças: ti/sistemas/cogtive.md
              - Integração Cogtive/SAP: ti/sistemas/cogtive.md
              - Lista de Preço Neogrid: ti/sistemas/cogtive.md
              - Módulo Manutenção: ti/sistemas/cogtive.md
              - OP Eletrônica: ti/sistemas/cogtive.md
              - Relatório PCP: ti/sistemas/cogtive.md
              - SE Suite - Gestão de Grupos de Usuários: ti/sistemas/cogtive.md
              - Tabela Preço Gerencial: ti/sistemas/cogtive.md
              - WMS - Fase 2: ti/sistemas/cogtive.md


  - Templates:
      - Modelo de Procedimento: docs/_templates/configuracao.md
      - Modelo de Configuração: templates/modelo-configuracao.md
      - Modelo de Norma: templates/modelo-norma.md
      - Modelo de Checklist: templates/modelo-checklist.md

  - Base de Conhecimento:
      - FAQ: base-de-conhecimento/faq.md
      - Troubleshooting: base-de-conhecimento/troubleshooting.md
      - Boas Práticas: base-conhecimento/boas-praticas.md
      - Glossário: base-de-conhecimento/glossario.md
